server:
  tomcat:
    uri-encoding: UTF-8
  port: 8060

logging:
  level:
    org.springframework.web: ERROR
    net.consensys: DEBUG
    net.consensys.configs: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %c: %M - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5p %c: %M - %m%n"
  file: /logs/application.log

ethereum:
  nodes:
    - name: default
      url: ${ETHEREUM_NODE_URL:http://localhost:8545}
      blockStrategy: POLL
  healthcheck:
    pollInterval: 2000
  blockStrategy: POLL

#eventFilters:
#  - id: RequestCreated
#    contractAddress: ${CONTRACT_ADDRESS:0x4aecf261541f168bb3ca65fa8ff5012498aac3b8}
#    eventSpecification:
#      eventName: RequestCreated
#      indexedParameterDefinitions:
#        - position: 0
#          type: BYTES32
#        - position: 1
#          type: ADDRESS
#      nonIndexedParameterDefinitions:
#        - position: 2
#          type: BYTES32
#    correlationId:
#      type: NON_INDEXED_PARAMETER
#      index: 0

#contractTransactionFilters:
#- nodeName: ${ETHEREUM_NETWORK:DefaultNetwork}
#  type: "FROM_ADDRESS"
#  transactionIdentifierValue: ${CONTRACT_ADDRESS_EM_TOKEN:0x0f8E7A681019Ec13EfE853a6Eca666E05b214Fd5}
#  statuses: ['CONFIRMED']
#- nodeName: ${ETHEREUM_NETWORK:DefaultNetwork}
#  type: "TO_ADDRESS"
#  transactionIdentifierValue: ${CONTRACT_ADDRESS_EM_TOKEN:0xfBAB8dE62002c86986C6e070BD3bB46BF983C74e}
#  statuses: ['FAILED']

eventStore:
  type: DB
  url: http://localhost:8081/api/rest/v1
  eventPath: /event
  latestBlockPath: /latestblock
database:
  type: SQL

broadcaster:
  type: KAFKA
  cache:
    expirationMillis: 6000000
  event:
    confirmation:
      numBlocksToWait: 12
      numBlocksToWaitForMissingTx: 100
  multiInstance: false

# For Kafka
zookeeper:
  address: ${ZOOKEEPER_ADDRESS:localhost:2181}
kafka:
  bootstrap:
    addresses: ${KAFKA_ADDRESSES:localhost:9092}
  topic:
    contractEvents: contract-events
    blockEvents: block-events
    eventeumEvents: eventeum-events
    transactionEvents: transaction-events

    partitions: 1
    replicationSets: 1

spring:
  rabbitmq:
    host: ${RABBIT_ADDRESS:localhost}
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://kratos-db-dev-env-new.cjqomv3qnd66.ap-southeast-1.rds.amazonaws.com:3306/eventeum
    username: kratos_dev_new
    password: Kratos12345
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        #see: https://stackoverflow.com/questions/36583185/spring-data-jpa-could-not-initialize-proxy-no-session-with-methods-marke
        enable_lazy_load_no_trans: true
        # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update
#     jdbc:
#       lob:
#         # For postgres, see: https://github.com/pgjdbc/pgjdbc/issues/1102
#         non_contextual_creation: true

rabbitmq:
  exchange: ThisIsAExchange
  routingKeyPrefix: thisIsRoutingKey

management:
  endpoints:
    web.base-path: /monitoring
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
